spring:
    freemarker:
        checkTemplateLocation: false
    sendgrid:
        api-key:
        properties:
            sender:
                name: Constantinos Giannacoulis
            username:
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_SMTP_USERNAME}
        password: ${MAIL_SMTP_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
            sender:
                name: Constantinos Giannacoulis
        protocol: smtp
        test-connection: false
    application:
        name: mail-service
server:
    port: ${random.int[10300,10399]}
