server:
    port: 8200
spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            discovery:
                locator:
                    lower-case-service-id: true
                    enabled: true
            routes:
                -   id: catalog-service
                    uri: lb://catalog-service
                    predicates:
                        - Path=/products/**
                        - Method=GET,POST,PUT,DELETE
                -   id: catalog-service
                    uri: lb://catalog-service
                    predicates:
                        - Path=/categories/**
                -   id: customer-service
                    uri: lb://customer-service
                    predicates:
                        - Path=/customers/**
                -   id: order-service
                    uri: lb://order-service
                    predicates:
                        - Path=/orders/**
    config:
        import: optional:configserver:http://localhost:8000

eureka:
    client:
        fetch-registry: true
        refresh:
            enable: false
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8100/eureka/
    instance:
        lease-renewal-interval-in-seconds: 30

management:
    endpoints:
        web:
            exposure:
                include: health, metrics
